[package]
name = "sidr"
license = "Apache-2.0"
readme = "README.md"

version = "0.8.0"
authors = ["Aon"]
edition = "2018"

[dependencies]
ese_parser_lib = { git = "https://github.com/strozfriedberg/ese_parser.git", tag="v0.1.0"}
sqlite = "0.30.4"
simple-error = "0.3.0"
chrono = "^0.4"
bitflags = "1.2.1"
clap = { version = "4.1.7", features = ["derive"] }
json = "0.12.4"

[dependencies.sqlite3-sys]
version = "0.14"
default-features = false

[[bin]]
name = "sidr"
path = "src/main.rs"
