[package]
name = "windows_search_artifact"
version = "0.1.0"
authors = ["Aon"]
edition = "2021"

[dependencies]
ese_parser_lib = { path = "../ese_parser/lib" }
sqlite = "0.30.4"
serde = { version = "*", features = ["derive"] }
clap = { version = "*", features = ["derive"] }
serde_yaml = "*"
ouroboros = "*"
num = "*"

simple-error = "*"
chrono = "0.4"
#libc = "*"
bitflags = "1.2.1"

[dependencies.sqlite3-sys]
version = "0.14"
default-features = false
