[package]
name = "windows_search_artifact"
version = "0.1.0"
authors = ["Aon"]
edition = "2021"
default-run = "windows_search_artifact"

[lib]
name = "wsa_lib"
path = "src/lib.rs"

[[bin]]
name = "external_cfg"
path = "src/bin/external_cfg.rs"

[dependencies]
ese_parser_lib = { git = "ssh://git@stash.strozfriedberg.com/asdf/ese_parser.git" }
sqlite = "0.30.4"
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
ouroboros = "*"
num = "*"

simple-error = "*"
chrono = "0.4"
#libc = "*"
bitflags = "1.2.1"
clap = { version = "4.1.7", features = ["derive"] }
log = "0.4"
env_logger = "*"
function_name = "*"
once_cell = "*"
multimap = "*"

[dependencies.sqlite3-sys]
version = "0.14"
default-features = false
